// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.legis.demo.domain;

import com.legis.demo.domain.Favorite;
import javax.persistence.Entity;

privileged aspect Favorite_Roo_Jpa_Entity {
    
    declare @type: Favorite: @Entity;
    
}
