// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.legis.demo.domain;

import com.legis.demo.domain.Publication;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect Publication_Roo_Configurable {
    
    declare @type: Publication: @Configurable;
    
}
