// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.legis.demo.domain;

import com.legis.demo.dao.ActivityDAO;
import com.legis.demo.domain.ActivityDataOnDemand;
import com.legis.demo.domain.ActivityIntegrationTest;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect ActivityIntegrationTest_Roo_IntegrationTest {
    
    declare @type: ActivityIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: ActivityIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: ActivityIntegrationTest: @Transactional;
    
    @Autowired
    ActivityDataOnDemand ActivityIntegrationTest.dod;
    
    @Autowired
    ActivityDAO ActivityIntegrationTest.activityDAO;
    
    @Test
    public void ActivityIntegrationTest.testCount() {
        Assert.assertNotNull("Data on demand for 'Activity' failed to initialize correctly", dod.getRandomActivity());
        long count = activityDAO.count();
        Assert.assertTrue("Counter for 'Activity' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void ActivityIntegrationTest.testFind() {
        Activity obj = dod.getRandomActivity();
        Assert.assertNotNull("Data on demand for 'Activity' failed to initialize correctly", obj);
        Long id = obj.getId_();
        Assert.assertNotNull("Data on demand for 'Activity' failed to provide an identifier", id);
        obj = activityDAO.findOne(id);
        Assert.assertNotNull("Find method for 'Activity' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Activity' returned the incorrect identifier", id, obj.getId_());
    }
    
    @Test
    public void ActivityIntegrationTest.testFindAll() {
        Assert.assertNotNull("Data on demand for 'Activity' failed to initialize correctly", dod.getRandomActivity());
        long count = activityDAO.count();
        Assert.assertTrue("Too expensive to perform a find all test for 'Activity', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Activity> result = activityDAO.findAll();
        Assert.assertNotNull("Find all method for 'Activity' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Activity' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void ActivityIntegrationTest.testFindEntries() {
        Assert.assertNotNull("Data on demand for 'Activity' failed to initialize correctly", dod.getRandomActivity());
        long count = activityDAO.count();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Activity> result = activityDAO.findAll(new org.springframework.data.domain.PageRequest(firstResult / maxResults, maxResults)).getContent();
        Assert.assertNotNull("Find entries method for 'Activity' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Activity' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void ActivityIntegrationTest.testFlush() {
        Activity obj = dod.getRandomActivity();
        Assert.assertNotNull("Data on demand for 'Activity' failed to initialize correctly", obj);
        Long id = obj.getId_();
        Assert.assertNotNull("Data on demand for 'Activity' failed to provide an identifier", id);
        obj = activityDAO.findOne(id);
        Assert.assertNotNull("Find method for 'Activity' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyActivity(obj);
        Integer currentVersion = obj.getVersion();
        activityDAO.flush();
        Assert.assertTrue("Version for 'Activity' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ActivityIntegrationTest.testSaveUpdate() {
        Activity obj = dod.getRandomActivity();
        Assert.assertNotNull("Data on demand for 'Activity' failed to initialize correctly", obj);
        Long id = obj.getId_();
        Assert.assertNotNull("Data on demand for 'Activity' failed to provide an identifier", id);
        obj = activityDAO.findOne(id);
        boolean modified =  dod.modifyActivity(obj);
        Integer currentVersion = obj.getVersion();
        Activity merged = activityDAO.save(obj);
        activityDAO.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId_(), id);
        Assert.assertTrue("Version for 'Activity' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ActivityIntegrationTest.testSave() {
        Assert.assertNotNull("Data on demand for 'Activity' failed to initialize correctly", dod.getRandomActivity());
        Activity obj = dod.getNewTransientActivity(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Activity' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Activity' identifier to be null", obj.getId_());
        try {
            activityDAO.save(obj);
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        activityDAO.flush();
        Assert.assertNotNull("Expected 'Activity' identifier to no longer be null", obj.getId_());
    }
    
    @Test
    public void ActivityIntegrationTest.testDelete() {
        Activity obj = dod.getRandomActivity();
        Assert.assertNotNull("Data on demand for 'Activity' failed to initialize correctly", obj);
        Long id = obj.getId_();
        Assert.assertNotNull("Data on demand for 'Activity' failed to provide an identifier", id);
        obj = activityDAO.findOne(id);
        activityDAO.delete(obj);
        activityDAO.flush();
        Assert.assertNull("Failed to remove 'Activity' with identifier '" + id + "'", activityDAO.findOne(id));
    }
    
}
