// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.legis.demo.domain;

import com.legis.demo.dao.AutorDAO;
import com.legis.demo.domain.AutorDataOnDemand;
import com.legis.demo.domain.AutorIntegrationTest;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect AutorIntegrationTest_Roo_IntegrationTest {
    
    declare @type: AutorIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: AutorIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: AutorIntegrationTest: @Transactional;
    
    @Autowired
    AutorDataOnDemand AutorIntegrationTest.dod;
    
    @Autowired
    AutorDAO AutorIntegrationTest.autorDAO;
    
    @Test
    public void AutorIntegrationTest.testCount() {
        Assert.assertNotNull("Data on demand for 'Autor' failed to initialize correctly", dod.getRandomAutor());
        long count = autorDAO.count();
        Assert.assertTrue("Counter for 'Autor' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void AutorIntegrationTest.testFind() {
        Autor obj = dod.getRandomAutor();
        Assert.assertNotNull("Data on demand for 'Autor' failed to initialize correctly", obj);
        Long id = obj.getId_();
        Assert.assertNotNull("Data on demand for 'Autor' failed to provide an identifier", id);
        obj = autorDAO.findOne(id);
        Assert.assertNotNull("Find method for 'Autor' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Autor' returned the incorrect identifier", id, obj.getId_());
    }
    
    @Test
    public void AutorIntegrationTest.testFindAll() {
        Assert.assertNotNull("Data on demand for 'Autor' failed to initialize correctly", dod.getRandomAutor());
        long count = autorDAO.count();
        Assert.assertTrue("Too expensive to perform a find all test for 'Autor', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Autor> result = autorDAO.findAll();
        Assert.assertNotNull("Find all method for 'Autor' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Autor' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void AutorIntegrationTest.testFindEntries() {
        Assert.assertNotNull("Data on demand for 'Autor' failed to initialize correctly", dod.getRandomAutor());
        long count = autorDAO.count();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Autor> result = autorDAO.findAll(new org.springframework.data.domain.PageRequest(firstResult / maxResults, maxResults)).getContent();
        Assert.assertNotNull("Find entries method for 'Autor' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Autor' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void AutorIntegrationTest.testFlush() {
        Autor obj = dod.getRandomAutor();
        Assert.assertNotNull("Data on demand for 'Autor' failed to initialize correctly", obj);
        Long id = obj.getId_();
        Assert.assertNotNull("Data on demand for 'Autor' failed to provide an identifier", id);
        obj = autorDAO.findOne(id);
        Assert.assertNotNull("Find method for 'Autor' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyAutor(obj);
        Integer currentVersion = obj.getVersion();
        autorDAO.flush();
        Assert.assertTrue("Version for 'Autor' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void AutorIntegrationTest.testSaveUpdate() {
        Autor obj = dod.getRandomAutor();
        Assert.assertNotNull("Data on demand for 'Autor' failed to initialize correctly", obj);
        Long id = obj.getId_();
        Assert.assertNotNull("Data on demand for 'Autor' failed to provide an identifier", id);
        obj = autorDAO.findOne(id);
        boolean modified =  dod.modifyAutor(obj);
        Integer currentVersion = obj.getVersion();
        Autor merged = autorDAO.save(obj);
        autorDAO.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId_(), id);
        Assert.assertTrue("Version for 'Autor' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void AutorIntegrationTest.testSave() {
        Assert.assertNotNull("Data on demand for 'Autor' failed to initialize correctly", dod.getRandomAutor());
        Autor obj = dod.getNewTransientAutor(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Autor' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Autor' identifier to be null", obj.getId_());
        try {
            autorDAO.save(obj);
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        autorDAO.flush();
        Assert.assertNotNull("Expected 'Autor' identifier to no longer be null", obj.getId_());
    }
    
    @Test
    public void AutorIntegrationTest.testDelete() {
        Autor obj = dod.getRandomAutor();
        Assert.assertNotNull("Data on demand for 'Autor' failed to initialize correctly", obj);
        Long id = obj.getId_();
        Assert.assertNotNull("Data on demand for 'Autor' failed to provide an identifier", id);
        obj = autorDAO.findOne(id);
        autorDAO.delete(obj);
        autorDAO.flush();
        Assert.assertNull("Failed to remove 'Autor' with identifier '" + id + "'", autorDAO.findOne(id));
    }
    
}
