// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.legis.demo.domain;

import com.legis.demo.dao.BookDAO;
import com.legis.demo.domain.Book;
import com.legis.demo.domain.BookDataOnDemand;
import com.legis.demo.domain.CategoryDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect BookDataOnDemand_Roo_DataOnDemand {
    
    declare @type: BookDataOnDemand: @Component;
    
    private Random BookDataOnDemand.rnd = new SecureRandom();
    
    private List<Book> BookDataOnDemand.data;
    
    @Autowired
    CategoryDataOnDemand BookDataOnDemand.categoryDataOnDemand;
    
    @Autowired
    BookDAO BookDataOnDemand.bookDAO;
    
    public Book BookDataOnDemand.getNewTransientBook(int index) {
        Book obj = new Book();
        setId(obj, index);
        setPublicationName(obj, index);
        setPublicationNumber(obj, index);
        return obj;
    }
    
    public void BookDataOnDemand.setId(Book obj, int index) {
        Long id = new Integer(index).longValue();
        obj.setId(id);
    }
    
    public void BookDataOnDemand.setPublicationName(Book obj, int index) {
        String publicationName = "publicationName_" + index;
        if (publicationName.length() > 20) {
            publicationName = publicationName.substring(0, 20);
        }
        obj.setPublicationName(publicationName);
    }
    
    public void BookDataOnDemand.setPublicationNumber(Book obj, int index) {
        Long publicationNumber = new Integer(index).longValue();
        obj.setPublicationNumber(publicationNumber);
    }
    
    public Book BookDataOnDemand.getSpecificBook(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Book obj = data.get(index);
        Long id = obj.getId_();
        return bookDAO.findOne(id);
    }
    
    public Book BookDataOnDemand.getRandomBook() {
        init();
        Book obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId_();
        return bookDAO.findOne(id);
    }
    
    public boolean BookDataOnDemand.modifyBook(Book obj) {
        return false;
    }
    
    public void BookDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = bookDAO.findAll(new org.springframework.data.domain.PageRequest(from / to, to)).getContent();
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Book' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Book>();
        for (int i = 0; i < 10; i++) {
            Book obj = getNewTransientBook(i);
            try {
                bookDAO.save(obj);
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            bookDAO.flush();
            data.add(obj);
        }
    }
    
}
