// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.legis.demo.domain;

import com.legis.demo.dao.NewsDAO;
import com.legis.demo.domain.CategoryDataOnDemand;
import com.legis.demo.domain.News;
import com.legis.demo.domain.NewsDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect NewsDataOnDemand_Roo_DataOnDemand {
    
    declare @type: NewsDataOnDemand: @Component;
    
    private Random NewsDataOnDemand.rnd = new SecureRandom();
    
    private List<News> NewsDataOnDemand.data;
    
    @Autowired
    CategoryDataOnDemand NewsDataOnDemand.categoryDataOnDemand;
    
    @Autowired
    NewsDAO NewsDataOnDemand.newsDAO;
    
    public News NewsDataOnDemand.getNewTransientNews(int index) {
        News obj = new News();
        setId(obj, index);
        setPublicationName(obj, index);
        setPublicationNumber(obj, index);
        return obj;
    }
    
    public void NewsDataOnDemand.setId(News obj, int index) {
        Long id = new Integer(index).longValue();
        obj.setId(id);
    }
    
    public void NewsDataOnDemand.setPublicationName(News obj, int index) {
        String publicationName = "publicationName_" + index;
        if (publicationName.length() > 20) {
            publicationName = publicationName.substring(0, 20);
        }
        obj.setPublicationName(publicationName);
    }
    
    public void NewsDataOnDemand.setPublicationNumber(News obj, int index) {
        Long publicationNumber = new Integer(index).longValue();
        obj.setPublicationNumber(publicationNumber);
    }
    
    public News NewsDataOnDemand.getSpecificNews(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        News obj = data.get(index);
        Long id = obj.getId_();
        return newsDAO.findOne(id);
    }
    
    public News NewsDataOnDemand.getRandomNews() {
        init();
        News obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId_();
        return newsDAO.findOne(id);
    }
    
    public boolean NewsDataOnDemand.modifyNews(News obj) {
        return false;
    }
    
    public void NewsDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = newsDAO.findAll(new org.springframework.data.domain.PageRequest(from / to, to)).getContent();
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'News' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<News>();
        for (int i = 0; i < 10; i++) {
            News obj = getNewTransientNews(i);
            try {
                newsDAO.save(obj);
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            newsDAO.flush();
            data.add(obj);
        }
    }
    
}
