// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.legis.demo.domain;

import com.legis.demo.dao.PublicationDAO;
import com.legis.demo.domain.PublicationDataOnDemand;
import com.legis.demo.domain.PublicationIntegrationTest;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect PublicationIntegrationTest_Roo_IntegrationTest {
    
    declare @type: PublicationIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: PublicationIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: PublicationIntegrationTest: @Transactional;
    
    @Autowired
    PublicationDataOnDemand PublicationIntegrationTest.dod;
    
    @Autowired
    PublicationDAO PublicationIntegrationTest.publicationDAO;
    
    @Test
    public void PublicationIntegrationTest.testCount() {
        Assert.assertNotNull("Data on demand for 'Publication' failed to initialize correctly", dod.getRandomPublication());
        long count = publicationDAO.count();
        Assert.assertTrue("Counter for 'Publication' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void PublicationIntegrationTest.testFind() {
        Publication obj = dod.getRandomPublication();
        Assert.assertNotNull("Data on demand for 'Publication' failed to initialize correctly", obj);
        Long id = obj.getId_();
        Assert.assertNotNull("Data on demand for 'Publication' failed to provide an identifier", id);
        obj = publicationDAO.findOne(id);
        Assert.assertNotNull("Find method for 'Publication' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Publication' returned the incorrect identifier", id, obj.getId_());
    }
    
    @Test
    public void PublicationIntegrationTest.testFindAll() {
        Assert.assertNotNull("Data on demand for 'Publication' failed to initialize correctly", dod.getRandomPublication());
        long count = publicationDAO.count();
        Assert.assertTrue("Too expensive to perform a find all test for 'Publication', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Publication> result = publicationDAO.findAll();
        Assert.assertNotNull("Find all method for 'Publication' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Publication' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void PublicationIntegrationTest.testFindEntries() {
        Assert.assertNotNull("Data on demand for 'Publication' failed to initialize correctly", dod.getRandomPublication());
        long count = publicationDAO.count();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Publication> result = publicationDAO.findAll(new org.springframework.data.domain.PageRequest(firstResult / maxResults, maxResults)).getContent();
        Assert.assertNotNull("Find entries method for 'Publication' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Publication' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void PublicationIntegrationTest.testFlush() {
        Publication obj = dod.getRandomPublication();
        Assert.assertNotNull("Data on demand for 'Publication' failed to initialize correctly", obj);
        Long id = obj.getId_();
        Assert.assertNotNull("Data on demand for 'Publication' failed to provide an identifier", id);
        obj = publicationDAO.findOne(id);
        Assert.assertNotNull("Find method for 'Publication' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyPublication(obj);
        Integer currentVersion = obj.getVersion();
        publicationDAO.flush();
        Assert.assertTrue("Version for 'Publication' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void PublicationIntegrationTest.testSaveUpdate() {
        Publication obj = dod.getRandomPublication();
        Assert.assertNotNull("Data on demand for 'Publication' failed to initialize correctly", obj);
        Long id = obj.getId_();
        Assert.assertNotNull("Data on demand for 'Publication' failed to provide an identifier", id);
        obj = publicationDAO.findOne(id);
        boolean modified =  dod.modifyPublication(obj);
        Integer currentVersion = obj.getVersion();
        Publication merged = publicationDAO.save(obj);
        publicationDAO.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId_(), id);
        Assert.assertTrue("Version for 'Publication' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void PublicationIntegrationTest.testSave() {
        Assert.assertNotNull("Data on demand for 'Publication' failed to initialize correctly", dod.getRandomPublication());
        Publication obj = dod.getNewTransientPublication(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Publication' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Publication' identifier to be null", obj.getId_());
        try {
            publicationDAO.save(obj);
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        publicationDAO.flush();
        Assert.assertNotNull("Expected 'Publication' identifier to no longer be null", obj.getId_());
    }
    
    @Test
    public void PublicationIntegrationTest.testDelete() {
        Publication obj = dod.getRandomPublication();
        Assert.assertNotNull("Data on demand for 'Publication' failed to initialize correctly", obj);
        Long id = obj.getId_();
        Assert.assertNotNull("Data on demand for 'Publication' failed to provide an identifier", id);
        obj = publicationDAO.findOne(id);
        publicationDAO.delete(obj);
        publicationDAO.flush();
        Assert.assertNull("Failed to remove 'Publication' with identifier '" + id + "'", publicationDAO.findOne(id));
    }
    
}
